FROM mysql:latest

ENV MYSQL_DATABASE=demo-shopping
ENV MYSQL_USER=developer
ENV MYSQL_PASSWORD=D3v3lop3r@2021
ENV MYSQL_ROOT_PASSWORD=S3cr3t@2021

# sudo docker build -t data-store:1.0 .
# sudo docker container run -d --name data-store-development -p 3309:3306 data-store:1.0